# -- DISPLAY SETTINGS --
# Turn on the E-ink display
CONFIG_ZMK_DISPLAY=y
# Force the E-ink screen to update properly
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
# Show battery percentage on the widget
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

# -- ZMK STUDIO SETTINGS --
# Enable ZMK Studio for real-time wireless key remapping
CONFIG_ZMK_STUDIO=y
# Protect your configuration (requires unlocking the keyboard to edit via Studio)
CONFIG_ZMK_STUDIO_LOCKING=n